### Get JWT Token and store it in a variable
# @name login
POST https://medipoint.decodaai.com/api/auth/token/ HTTP/1.1
content-type: application/json

{
    "email": "osama4@gmail.com",
    "password": "Anas775995183"
}

### Extract the token from the response and store it in a variable
@access = {{login.response.body.access}}

### Update user profile using the stored token
PUT https://medipoint.decodaai.com/api/auth/me/ HTTP/1.1
Authorization: Bearer {{access}}
content-type: application/json

{
  "status":"A"
}